"""add_pix_payment_table_and_user_tax_id

Revision ID: e9510783e54b
Revises: b77fa22bfa12
Create Date: 2025-12-20 14:45:44.206381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9510783e54b'
down_revision: Union[str, None] = 'b77fa22bfa12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Using String instead of Enum for the 'plan' column to avoid Postgres type conflicts
    # Since UserPlan enum uses string values, this is compatible.
    op.create_table('pix_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('qr_code_id', sa.String(length=50), nullable=True),
    sa.Column('qr_code_text', sa.Text(), nullable=True),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pix_payments_id'), 'pix_payments', ['id'], unique=False)
    op.create_index(op.f('ix_pix_payments_order_id'), 'pix_payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_pix_payments_reference_id'), 'pix_payments', ['reference_id'], unique=True)
    op.create_index(op.f('ix_pix_payments_status'), 'pix_payments', ['status'], unique=False)
    op.create_index(op.f('ix_pix_payments_user_id'), 'pix_payments', ['user_id'], unique=False)
    
    # Safe drop for existing tables if they exist
    op.execute('DROP TABLE IF EXISTS pix_charges CASCADE')
    op.execute('DROP TABLE IF EXISTS pix_transactions CASCADE')
    
    op.add_column('users', sa.Column('tax_id', sa.String(length=14), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tax_id')
    op.drop_index(op.f('ix_pix_payments_user_id'), table_name='pix_payments')
    op.drop_index(op.f('ix_pix_payments_status'), table_name='pix_payments')
    op.drop_index(op.f('ix_pix_payments_reference_id'), table_name='pix_payments')
    op.drop_index(op.f('ix_pix_payments_order_id'), table_name='pix_payments')
    op.drop_index(op.f('ix_pix_payments_id'), table_name='pix_payments')
    op.drop_table('pix_payments')
    # ### end Alembic commands ###
