"""add_pix_payment_table_and_user_tax_id

Revision ID: e9510783e54b
Revises: b77fa22bfa12
Create Date: 2025-12-20 14:45:44.206381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9510783e54b'
down_revision: Union[str, None] = 'b77fa22bfa12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pix_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.Enum('free', 'premium', 'enterprise', name='userplan', create_type=False), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('qr_code_id', sa.String(length=50), nullable=True),
    sa.Column('qr_code_text', sa.Text(), nullable=True),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pix_payments_id'), 'pix_payments', ['id'], unique=False)
    op.create_index(op.f('ix_pix_payments_order_id'), 'pix_payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_pix_payments_reference_id'), 'pix_payments', ['reference_id'], unique=True)
    op.create_index(op.f('ix_pix_payments_status'), 'pix_payments', ['status'], unique=False)
    op.create_index(op.f('ix_pix_payments_user_id'), 'pix_payments', ['user_id'], unique=False)
    op.drop_index(op.f('ix_pix_charges_status'), table_name='pix_charges')
    op.drop_index(op.f('ix_pix_charges_txid'), table_name='pix_charges')
    op.drop_index(op.f('ix_pix_charges_user_id'), table_name='pix_charges')
    op.drop_table('pix_charges')
    op.drop_index(op.f('ix_pix_transactions_id'), table_name='pix_transactions')
    op.drop_index(op.f('ix_pix_transactions_lxpay_transaction_id'), table_name='pix_transactions')
    op.drop_index(op.f('ix_pix_transactions_status'), table_name='pix_transactions')
    op.drop_table('pix_transactions')
    op.add_column('users', sa.Column('tax_id', sa.String(length=14), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tax_id')
    op.create_table('pix_transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('lxpay_transaction_id', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('plan_type', sa.VARCHAR(), nullable=False),
    sa.Column('qr_code', sa.TEXT(), nullable=True),
    sa.Column('qr_code_image', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pix_transactions_status'), 'pix_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_pix_transactions_lxpay_transaction_id'), 'pix_transactions', ['lxpay_transaction_id'], unique=1)
    op.create_index(op.f('ix_pix_transactions_id'), 'pix_transactions', ['id'], unique=False)
    op.create_table('pix_charges',
    sa.Column('txid', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('copy_paste_code', sa.TEXT(), nullable=False),
    sa.Column('qr_code_image', sa.TEXT(), nullable=True),
    sa.Column('plan_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('duration_months', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('txid')
    )
    op.create_index(op.f('ix_pix_charges_user_id'), 'pix_charges', ['user_id'], unique=False)
    op.create_index(op.f('ix_pix_charges_txid'), 'pix_charges', ['txid'], unique=False)
    op.create_index(op.f('ix_pix_charges_status'), 'pix_charges', ['status'], unique=False)
    op.drop_index(op.f('ix_pix_payments_user_id'), table_name='pix_payments')
    op.drop_index(op.f('ix_pix_payments_status'), table_name='pix_payments')
    op.drop_index(op.f('ix_pix_payments_reference_id'), table_name='pix_payments')
    op.drop_index(op.f('ix_pix_payments_order_id'), table_name='pix_payments')
    op.drop_index(op.f('ix_pix_payments_id'), table_name='pix_payments')
    op.drop_table('pix_payments')
    # ### end Alembic commands ###
