"""add_status_message_to_copy_jobs

Revision ID: 5782be5cc06b
Revises: 0141e12a4b13
Create Date: 2026-01-21 08:41:38.111801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_status_message_to_copy_jobs

Revision ID: 5782be5cc06b
Revises: 0141e12a4b13
Create Date: 2026-01-21 08:41:38.111801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5782be5cc06b'
down_revision: Union[str, None] = '0141e12a4b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copy_jobs', sa.Column('status_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copy_jobs', 'status_message')
    # ### end Alembic commands ###
