"""verify_models_up_to_date

Revision ID: 1ae0a2b4f203
Revises: f91eb8989f1e
Create Date: 2026-01-29 09:30:24.407327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae0a2b4f203'
down_revision: Union[str, None] = 'f91eb8989f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pix_payments', schema=None) as batch_op:
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('free', 'premium', 'enterprise', name='userplan'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pix_payments', schema=None) as batch_op:
        batch_op.alter_column('plan',
               existing_type=sa.Enum('free', 'premium', 'enterprise', name='userplan'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
