"""Add TempAuthSession model

Revision ID: 0141e12a4b13
Revises: 113cc553e35a
Create Date: 2026-01-14 21:35:01.804321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0141e12a4b13'
down_revision: Union[str, None] = '113cc553e35a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_auth_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('api_id', sa.String(length=100), nullable=False),
    sa.Column('api_hash', sa.String(length=100), nullable=False),
    sa.Column('phone_code_hash', sa.String(length=255), nullable=False),
    sa.Column('session_file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_auth_sessions_id'), 'temp_auth_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_temp_auth_sessions_session_key'), 'temp_auth_sessions', ['session_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_auth_sessions_session_key'), table_name='temp_auth_sessions')
    op.drop_index(op.f('ix_temp_auth_sessions_id'), table_name='temp_auth_sessions')
    op.drop_table('temp_auth_sessions')
    # ### end Alembic commands ###
